---
apiVersion: v1
kind: Namespace
metadata:
  name: exec-1-roll-update

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v1
  namespace: exec-1-roll-update
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: nodejs
        image: luksa/kubia:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8080
